apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-2048
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-2048
  template:
    metadata:
      labels:
        app: game-2048
    spec:
      containers:
      - name: game-container
        # משתמשים ב-Image הרשמי שראינו שעובד אצלך בשרת
        image: nginx:latest
        ports:
        - containerPort: 80
        # כאן אנחנו "מזריקים" את המשחק לתוך ה-Nginx בלי להזדקק לאימג' חיצוני נוסף
        command: ["/bin/sh", "-c"]
        args:
          - |
            apt-get update && apt-get install -y git &&
            rm -rf /usr/share/nginx/html/* &&
            git clone https://github.com/gabrielecirulli/2048.git /usr/share/nginx/html/ &&
            nginx -g 'daemon off;'
---
apiVersion: v1
kind: Service
metadata:
  name: game-service
spec:
  selector:
    app: game-2048
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
