apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  labels:
{{- include "spring.labels" . | nindent 4 }}
data:
  dbname: {{ .Values.dbname | default "musicdb" }}
  dbtable: {{ .Values.dbtable | default "songs" }}
