apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  labels:
{{- include "spring.labels" . | nindent 4 }}
spec:
  # לוגיקה לפי שקף 163 (אם LOCAL אז NodePort)
  type: {{ if eq .Values.env "LOCAL" }}NodePort{{ else }}LoadBalancer{{ end }}
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ .Chart.Name }}
